<?xml version="1.0"?>
<package format="2">
  <name>iai_dualarm_description</name>
  <version>0.0.0</version>
  <description>The iai_dualarm_description package</description>

  <maintainer email="huerkamp@uni-bremen.de">huerkamp</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>ur_robot_driver</exec_depend>
  <exec_depend>griplink</exec_depend>
  <exec_depend>griplink_interfaces</exec_depend>
  <exec_depend>wpg_300_120_description</exec_depend>
  <exec_depend>iai_ur_description</exec_depend>
  <!-- The export tag contains other, unspecified, tags -->
<export>                               
   <build_type>ament_cmake</build_type> 
</export> 

</package>
