controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_io_and_status_controller:
      type: ur_controllers/GPIOController

    right_io_and_status_controller:
      type: ur_controllers/GPIOController

    left_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    right_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    left_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    right_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    right_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    left_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    right_forward_position_controller:
      type: position_controllers/JointGroupPositionController


left_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "left_"

right_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "right_"

left_io_and_status_controller:
  ros__parameters:
    tf_prefix: "left_"

right_io_and_status_controller:
  ros__parameters:
    tf_prefix: "right_"

left_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: left_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: left_tool0
    topic_name: left_ft_data

right_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: right_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: right_tool0
    topic_name: right_ft_data


left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      left_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      left_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      left_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      right_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      right_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      right_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

left_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      left_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      left_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      left_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      left_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: left_speed_scaling/speed_scaling_factor

right_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      right_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      right_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      right_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      right_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: right_speed_scaling/speed_scaling_factor

left_forward_velocity_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    interface_name: velocity

right_forward_velocity_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    interface_name: velocity

left_forward_position_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

right_forward_position_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint